#!/bin/bash -ex

[ "$1" = "-R" ] && { "$0" -D && "$0" ; } && exit 0

[ -z "$1" -o "$1" = "-D" ] || exit 1

echo 'Include ~/.ssh/muon.conf' > ssh/.ssh/config

stow -v -t $HOME            $1 bash
stow -v -t $HOME            $1 git
stow -v -t $HOME            $1 tmux
stow -v -t $HOME            $1 vim
stow -v -t $HOME            $1 pip
stow -v -t $HOME/.local/bin $1 scripts
stow -v -t $HOME/.local/bin $1 media
stow -v -t $HOME/.ssh       $1 ssh
