#!/bin/bash -ex

[ -z "$1" -o "$1" = "-D" -o "$1" = "-R" ] || exit 1

# WSL's Ubuntu 16.04 SSH does not support Include yet... (>_<)
#echo 'Include ~/.ssh/nb-xps08.conf' > ssh/.ssh/config

mkdir -pv \
    $HOME/.ssh \
    $HOME/.vim

stow -v -t $HOME            $1 bash
stow -v -t $HOME            $1 git
stow -v -t $HOME            $1 tmux
stow -v -t $HOME/.ssh       $1 ssh
stow -v -t $HOME/.vim       $1 vim
stow -v -t $HOME            $1 pip
stow -v -t $HOME/.local/bin $1 scripts

./fzf-get

sudo \
stow -v -t '/usr/local'     $1 fzf

# Oh well, just do a ranzige hack for now
[ -f ~/.ssh/nb-xps08.conf ] &&
cat ~/.ssh/nb-xps08.conf \
    | sed 's/Include //' \
    | sed "s_~_${HOME}_" \
    | xargs cat \
    > ~/.ssh/config
