#!/bin/bash -e

test -z "$1" -o "$1" = "-D" || exit 1

stow -v -t $HOME $1 bash
stow -v -t $HOME $1 git
stow -v -t $HOME $1 vim

mkdir -pv $HOME/.local/bin
stow -v -t $HOME/.local/bin $1 scripts
stow -v -t $HOME/.local/bin $1 scripts
