#!/bin/bash -e

test -z "$1" -o "$1" = "-D" || exit 1

stow -v -t $HOME            $1 bash
stow -v -t $HOME            $1 git
stow -v -t $HOME            $1 vim
stow -v -t $HOME            $1 pip
stow -v -t $HOME            $1 scripts
stow -v -t $HOME            $1 scripts-media
