#!/bin/bash

#
# set editor
#

export EDITOR=vim

#
# make terminal 256-color
#

case $TERM in
    xterm)
        TERM=xterm-256color
        ;;
    screen)
        TERM=screen-256color
        ;;
esac

#
# add ~/bin to path if it's not already there
#

if [[ :$PATH: != *:$HOME/bin:* ]]; then
    PATH=$HOME/bin:$PATH
fi
