#!/bin/bash

case `uname` in
    Linux)
        LN="ln -sfTi"
        ;;

    Darwin)
        LN="ln -sfFi"
        ;;
esac

case `basename $0` in

    deploy)
        $LN $(pwd)/bin                 ~/bin
        $LN $(pwd)/vim                 ~/.vim
        $LN $(pwd)/vim/vimrc           ~/.vimrc
        $LN $(pwd)/bash_aliases        ~/.bash_aliases
        $LN $(pwd)/bash_settings       ~/.bash_settings
        $LN $(pwd)/gitconfig           ~/.gitconfig
        ;;

    undeploy)
        rm ~/bin
        rm ~/.bash_aliases
        rm ~/.bash_settings
        rm ~/.vim
        rm ~/.vimrc
        rm ~/.gitconfig
        ;;

    redeploy)
        ./undeploy
        ./deploy
        ;;

esac

