#!/bin/bash

case `uname` in
    Linux)
        LN=-sfTi
        ;;

    Darwin)
        LN=-sfFi
        ;;
esac

case `basename $0` in

    deploy)
        ln $LN $(pwd)/bin               ~/bin
        ln $LN $(pwd)/vim               ~/.vim
        ln $LN $(pwd)/vim/vimrc         ~/.vimrc
        ln $LN $(pwd)/bash_aliases      ~/.bash_aliases
        ln $LN $(pwd)/bash_settings     ~/.bash_settings
        ./git-config deploy
        ;;

    undeploy)
        rm ~/bin
        rm ~/.bash_aliases
        rm ~/.bash_settings
        rm ~/.vim
        rm ~/.vimrc
        ./git-config undeploy
        ;;

esac

