#!/bin/bash

case "$(uname)" in
    (Linux)
        LN="ln -sfTiv"
        ;;

    (CYGWIN_NT*)
        LN="ln -sfTiv"
        ;;

    (Darwin)
        LN="ln -sfFiv"
        ;;

    (*)
        echo "Unrecognized uname: $(uname)"
        exit 1
esac

case "$1" in

    deploy)
        $LN $(pwd)/bin                 ~/bin
        $LN $(pwd)/vim                 ~/.vim
        $LN $(pwd)/bash_logout         ~/.bash_logout
        $LN $(pwd)/bash_settings       ~/.bash_settings
        $LN $(pwd)/gitconfig           ~/.gitconfig
        $LN $(pwd)/tmux.conf           ~/.tmux.conf

        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        $LN $(pwd)/sshconfig.d         ~/.ssh/config.d
        ;;

    undeploy)
        rm -fv ~/bin
        rm -fv ~/.vim
        rm -fv ~/.bash_logout
        rm -fv ~/.bash_settings
        rm -fv ~/.gitconfig
        rm -fv ~/.tmux.conf

        rm -fv ~/.ssh/config.d
        ;;

    redeploy)
        "$0" undeploy
        "$0" deploy
        ;;

    *)
        echo "usage: $(basename $0) deploy|undeploy|redeploy" 1>&2
        exit 1
        ;;

esac
