" editing options
set hidden
set tabstop=4 shiftwidth=4 expandtab
set nowrap
set laststatus=2 modeline
set incsearch hlsearch
set number
set wildmenu
set noswapfile
set showcmd

" enable filetype magic
syntax on
filetype on
filetype plugin on
filetype indent on

" configure fzf
let g:fzf_command_prefix="Fzf"

" configure jedi
let g:jedi#popup_on_dot             = 0
let g:jedi#completions_command      = "<C-Space>"
let g:jedi#documentation_command    = "K"
let g:jedi#goto_assignments_command = "<LEADER>pa"
let g:jedi#goto_command             = "<LEADER>pg"
let g:jedi#goto_definitions_command = "<LEADER>pd"
let g:jedi#rename_command           = "<LEADER>pr"
let g:jedi#usages_command           = "<LEADER>pu"

" load plugins
runtime bundle/pathogen/autoload/pathogen.vim
silent! execute pathogen#infect()

" colors
if $TERM == "xterm-256color"
    set t_Co=256
    colorscheme landscape
    highlight StatusLine ctermfg=121 ctermbg=240
    highlight TabLineFill cterm=NONE
    highlight TabLineSel ctermfg=120
else
    set t_Co=16
    colorscheme murphy
    highlight Folded ctermfg=darkgray
endif

" leader key is hard to reach on mobile
set timeoutlen=2500

" editing .vimrc
nnoremap <LEADER>ce :edit $MYVIMRC<CR>
nnoremap <LEADER>cs :source $MYVIMRC<CR>

" buffer switching
nnoremap <LEADER>a :bprev<CR>
nnoremap <LEADER>s :bnext<CR>

nnoremap <LEADER>bw :bwipe<CR>

nnoremap <LEADER>g :grep -R <C-r><C-w> *<CR>:copen<CR>

nnoremap <LEADER>ff     :FzfFiles<CR>
nnoremap <LEADER>fg     :FzfGFiles<CR>
nnoremap <LEADER>fgf    :FzfGFiles<CR>
nnoremap <LEADER>fb     :FzfBuffers<CR>
nnoremap <LEADER>fbb    :FzfBuffers<CR>
nnoremap <LEADER>fc     :FzfColors<CR>
nnoremap <LEADER>fl     :FzfLines<CR>
nnoremap <LEADER>fbl    :FzfBLines<CR>
nnoremap <LEADER>ft     :FzfTags<CR>
nnoremap <LEADER>fbt    :FzfBTags<CR>
nnoremap <LEADER>fm     :FzfMarks<CR>
nnoremap <LEADER>fw     :FzfWindows<CR>
nnoremap <LEADER>fw     :FzfWindows<CR>
nnoremap <LEADER>fh     :FzfHistory<CR>
nnoremap <LEADER>fhf    :FzfHistory<CR>
nnoremap <LEADER>fh:    :FzfHistory:<CR>
nnoremap <LEADER>fh/    :FzfHistory/<CR>
nnoremap <LEADER>fgc    :FzfCommits<CR>
nnoremap <LEADER>fgb    :FzfBCommits<CR>
nnoremap <LEADER>f:     :FzfCommands<CR>
nnoremap <LEADER>fm     :FzfMaps<CR>
nnoremap <LEADER>fH     :FzfHelptags<CR>
nnoremap <LEADER>fF     :FzfFiletypes<CR>

nnoremap <F5> :!./%<CR>
nnoremap <F6> :!pytest %<CR>

" statusline
set statusline=[%n]%m%r%h%w\ %t\ [%{&ff}]\ %y\ %=%{fugitive#head(7)}\ 0x%04.4B\ %v\ %l/%L\ %p%%

" automatically remove trailing whitespace to make Git happy
augroup  trailing_whitespace
autocmd! trailing_whitespace
autocmd  trailing_whitespace BufRead  *.md   let b:preserve_trailing_ws=1
autocmd  trailing_whitespace BufRead  *.diff let b:preserve_trailing_ws=1
autocmd  trailing_whitespace BufWrite *      if !exists("b:preserve_trailing_ws")
                                             \ | let cursor = getpos(".")
                                             \ | %s/\s\+$//e
                                             \ | call setpos(".", cursor)
                                             \ | endif
augroup  end

" automatically remove trailing newlines to make Git happy
augroup  trailing_newlines
autocmd! trailing_newlines
autocmd  trailing_newlines BufRead  *.diff let b:preserve_trailing_nl=1
autocmd  trailing_newlines BufWrite *      if !exists("b:preserve_trailing_nl")
                                           \ | let cursor = getpos(".")
                                           \ | %s/\($\n\s*\)\+\%$//e
                                           \ | call setpos(".", cursor)
                                           \ | endif
augroup  end
