" editing options
set hidden
set tabstop=4 shiftwidth=4 expandtab nowrap
set laststatus=2 modeline
set incsearch hlsearch
set number
set wildmenu

" colors!
set t_Co=16
colorscheme murphy
syntax on

" load plugins
let g:pathogen_disabled=["pathogen"]
silent! execute pathogen#infect()

let mapleader = ','

" editing .vimrc
nnoremap <LEADER>ce :edit $MYVIMRC<CR>
nnoremap <LEADER>cs :source $MYVIMRC<CR>

" buffer switching
nnoremap <LEADER>a :bprev<CR>
nnoremap <LEADER>f :bnext<CR>

" statusline
set statusline=[%n]%m%r\ %F%h%w\ [%{&ff}]\ %y\ %=%{fugitive#head(7)}\ 0x%04.4B\ %v\ %l/%L\ %p%% 
