" editing options
set hidden
set tabstop=4 shiftwidth=4 expandtab nowrap
set laststatus=2 modeline
set incsearch hlsearch
set number
set wildmenu
set noswapfile

" colors!
set t_Co=16
colorscheme murphy
syntax on

" load plugins
let g:fzf_command_prefix="Fzf"
let g:fzf_layout={ 'right': '~40%' }
let g:pathogen_disabled=["pathogen"]
silent! execute pathogen#infect()

" leader key is hard to reach on mobile
set timeoutlen=2500
" let mapleader = ','

" editing .vimrc
nnoremap <LEADER>ce :edit $MYVIMRC<CR>
nnoremap <LEADER>cs :source $MYVIMRC<CR>

" buffer switching
nnoremap <LEADER>a :bprev<CR>
nnoremap <LEADER>s :bnext<CR>

nnoremap <LEADER>bw :bwipe<CR>

nnoremap <LEADER>g :grep -R <C-r><C-w> *<CR>:copen<CR>

nnoremap <LEADER>ff     :FzfFiles<CR>
nnoremap <LEADER>fg     :FzfGFiles<CR>
nnoremap <LEADER>fgf    :FzfGFiles<CR>
nnoremap <LEADER>fb     :FzfBuffers<CR>
nnoremap <LEADER>fbb    :FzfBuffers<CR>
nnoremap <LEADER>fc     :FzfColors<CR>
nnoremap <LEADER>fl     :FzfLines<CR>
nnoremap <LEADER>fbl    :FzfBLines<CR>
nnoremap <LEADER>ft     :FzfTags<CR>
nnoremap <LEADER>fbt    :FzfBTags<CR>
nnoremap <LEADER>fm     :FzfMarks<CR>
nnoremap <LEADER>fw     :FzfWindows<CR>
nnoremap <LEADER>fw     :FzfWindows<CR>
nnoremap <LEADER>fh     :FzfHistory<CR>
nnoremap <LEADER>fhf    :FzfHistory<CR>
nnoremap <LEADER>fh:    :FzfHistory:<CR>
nnoremap <LEADER>fh/    :FzfHistory/<CR>
nnoremap <LEADER>fgc    :FzfCommits<CR>
nnoremap <LEADER>fgb    :FzfBCommits<CR>
nnoremap <LEADER>fgb    :FzfBCommits<CR>
nnoremap <LEADER>f:     :FzfCommands<CR>
nnoremap <LEADER>fm     :FzfMaps<CR>
nnoremap <LEADER>fH     :FzfHelptags<CR>
nnoremap <LEADER>fF     :FzfFiletypes<CR>

nnoremap <F5> :!./%<CR>
nnoremap <F6> :!pytest %<CR>

" statusline
set statusline=[%n]%m%r\ %F%h%w\ [%{&ff}]\ %y\ %=%{fugitive#head(7)}\ 0x%04.4B\ %v\ %l/%L\ %p%% 
