" editing options
set hidden
set tabstop=4 shiftwidth=4 expandtab nowrap
set laststatus=2 modeline
set incsearch hlsearch
set number
set wildmenu
set noswapfile

" colors!
set t_Co=16
colorscheme murphy
syntax on

" load plugins
let g:fzf_command_prefix="Fzf"
let g:pathogen_disabled=["pathogen"]
silent! execute pathogen#infect()

" let mapleader = ','

" editing .vimrc
nnoremap <LEADER>ce :edit $MYVIMRC<CR>
nnoremap <LEADER>cs :source $MYVIMRC<CR>

" buffer switching
nnoremap <LEADER>a :bprev<CR>
nnoremap <LEADER>s :bnext<CR>

nnoremap <LEADER>bw :bwipe<CR>

nnoremap <LEADER>g :grep -R <C-r><C-w> *<CR>:copen<CR>

nnoremap <F5> :!./%<CR>
nnoremap <F6> :!pytest %<CR>

" statusline
set statusline=[%n]%m%r\ %F%h%w\ [%{&ff}]\ %y\ %=%{fugitive#head(7)}\ 0x%04.4B\ %v\ %l/%L\ %p%% 
