#!/bin/bash
export \
    cores="$(grep -c processor /proc/cpuinfo)" \
    bitrate="${1:-320}"
find . -name '*.flac' -print0 \
    | xargs -0 -n 1 -P $cores bash -c \
        'echo $0; flac --silent --decode --stdout "$0" | lame --silent -b $bitrate "-" "${0/.flac/.mp3}" &> /dev/null'
