#!/bin/bash
export \
    cores="$(grep -c processor /proc/cpuinfo)" \
    bitrate="${1:-320}"
find . -name '*.wav' -print0 \
    | xargs -0 -n 1 -P $cores bash -c 'echo $0; lame --silent -b $bitrate "$0" "${0/.wav/.mp3}" &> /dev/null'
