#!/bin/bash
curl -s 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt' \
    | sed -n "2,\$ { s/.*/${1?missing name}.\\L&./ ; p }" \
    | { while read domain ; do
            dig +noall +answer @${2:-8.8.8.8} $domain ANY \
                | ifne -n echo $domain &
        done
        wait
    }
