#!/usr/bin/gawk -f

BEGIN { RS="-+(BEGIN|END) CERTIFICATE-+"
        CMD="openssl x509 -subject -issuer -dates -serial" }

NR % 2 == 1 { x=RT }

NR % 2 == 0 { print x $0 RT | CMD
              close(CMD) }
